"""add_audit_run_failure_diagnostics

Revision ID: 45c74acfc5a8
Revises: 470e27a69f66
Create Date: 2026-06-22 20:00:05.217261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c74acfc5a8'
down_revision: Union[str, None] = '470e27a69f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_runs', sa.Column('failed_stage', sa.String(length=100), nullable=True))
    op.add_column('audit_runs', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('audit_runs', sa.Column('failure_stack_trace', sa.Text(), nullable=True))
    op.add_column('audit_runs', sa.Column('last_successful_step', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_runs', 'last_successful_step')
    op.drop_column('audit_runs', 'failure_stack_trace')
    op.drop_column('audit_runs', 'failure_reason')
    op.drop_column('audit_runs', 'failed_stage')
    # ### end Alembic commands ###
