"""add_report_urls_to_generated_reports

Revision ID: 54710890f1c2
Revises: 45c74acfc5a8
Create Date: 2026-06-22 23:04:36.150355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54710890f1c2'
down_revision: Union[str, None] = '45c74acfc5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_reports', sa.Column('student_report_url', sa.String(length=500), nullable=True))
    op.add_column('generated_reports', sa.Column('company_report_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_reports', 'company_report_url')
    op.drop_column('generated_reports', 'student_report_url')
    # ### end Alembic commands ###
