"""replace_generated_report_with_project_report

Revision ID: 8c6d20815cb7
Revises: c6ae2c7b6df8
Create Date: 2026-06-24 10:42:20.485978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c6d20815cb7'
down_revision: Union[str, None] = 'c6ae2c7b6df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_run_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('completion_score', sa.Float(), nullable=False),
    sa.Column('security_score', sa.Float(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('uiux_score', sa.Float(), nullable=False),
    sa.Column('code_quality_score', sa.Float(), nullable=False),
    sa.Column('production_readiness', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('report_url', sa.String(length=1000), nullable=True),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('json_url', sa.String(length=1000), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('generated_reports')
    op.add_column('audit_runs', sa.Column('project_report_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'audit_runs', 'project_reports', ['project_report_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_runs', type_='foreignkey')
    op.drop_column('audit_runs', 'project_report_id')
    op.create_table('generated_reports',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('completion_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('student_report', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('company_report', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('student_report_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('company_report_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('generated_reports_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('generated_reports_pkey'))
    )
    op.drop_table('project_reports')
    # ### end Alembic commands ###
