"""initial_schema

Revision ID: 8f0a31361305
Revises: 
Create Date: 2026-06-22 15:45:58.901008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0a31361305'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repo_url', sa.String(length=512), nullable=False),
    sa.Column('commit_sha', sa.String(length=100), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_analyses_repo_url'), 'github_analyses', ['repo_url'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repository_url', sa.String(length=512), nullable=True),
    sa.Column('prd_url', sa.String(length=512), nullable=True),
    sa.Column('deployment_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rbac_enabled', sa.Boolean(), nullable=False),
    sa.Column('admin_url', sa.String(length=512), nullable=True),
    sa.Column('user_url', sa.String(length=512), nullable=True),
    sa.Column('auth_required', sa.Boolean(), nullable=False),
    sa.Column('login_url', sa.String(length=512), nullable=True),
    sa.Column('secret_reference', sa.String(length=36), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('parent_token_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('audit_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('triggered_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('student_report', sa.JSON(), nullable=False),
    sa.Column('company_report', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_audit_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_run_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('login_success', sa.Boolean(), nullable=False),
    sa.Column('logout_success', sa.Boolean(), nullable=False),
    sa.Column('session_persisted', sa.Boolean(), nullable=False),
    sa.Column('invalid_password_rejected', sa.Boolean(), nullable=False),
    sa.Column('empty_creds_rejected', sa.Boolean(), nullable=False),
    sa.Column('routes_protected', sa.Boolean(), nullable=False),
    sa.Column('redirect_after_login', sa.String(length=512), nullable=True),
    sa.Column('redirect_after_logout', sa.String(length=512), nullable=True),
    sa.Column('protected_routes_found', sa.Integer(), nullable=False),
    sa.Column('protected_routes_audited', sa.Integer(), nullable=False),
    sa.Column('auth_score', sa.Float(), nullable=False),
    sa.Column('login_url_used', sa.String(length=512), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('protected_routes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('audit_run_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('function_name', sa.String(length=255), nullable=True),
    sa.Column('line_range', sa.String(length=50), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('screenshot_url', sa.String(length=1024), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rbac_audit_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_run_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('rbac_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('auth_score', sa.Float(), nullable=False),
    sa.Column('authz_score', sa.Float(), nullable=False),
    sa.Column('session_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('role_coverage_matrix', sa.Text(), nullable=True),
    sa.Column('violations', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('audit_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('rbac_audit_results')
    op.drop_table('evidences')
    op.drop_table('auth_audit_results')
    op.drop_table('generated_reports')
    op.drop_table('audit_runs')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_github_analyses_repo_url'), table_name='github_analyses')
    op.drop_table('github_analyses')
    # ### end Alembic commands ###
