"""Add LLM Provider Config and Audit Trace

Revision ID: c6ae2c7b6df8
Revises: 54710890f1c2
Create Date: 2026-06-23 15:38:12.108309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ae2c7b6df8'
down_revision: Union[str, None] = '54710890f1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_provider_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_provider_configs_provider_name'), 'llm_provider_configs', ['provider_name'], unique=True)
    op.add_column('audit_runs', sa.Column('llm_provider_used', sa.String(length=50), nullable=True))
    op.add_column('audit_runs', sa.Column('llm_model_used', sa.String(length=100), nullable=True))
    op.add_column('audit_runs', sa.Column('llm_fallback_triggered', sa.Boolean(), nullable=True))
    op.add_column('audit_runs', sa.Column('llm_prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('audit_runs', sa.Column('llm_completion_tokens', sa.Integer(), nullable=True))
    op.add_column('audit_runs', sa.Column('llm_latency_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_runs', 'llm_latency_ms')
    op.drop_column('audit_runs', 'llm_completion_tokens')
    op.drop_column('audit_runs', 'llm_prompt_tokens')
    op.drop_column('audit_runs', 'llm_fallback_triggered')
    op.drop_column('audit_runs', 'llm_model_used')
    op.drop_column('audit_runs', 'llm_provider_used')
    op.drop_index(op.f('ix_llm_provider_configs_provider_name'), table_name='llm_provider_configs')
    op.drop_table('llm_provider_configs')
    # ### end Alembic commands ###
